spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema1
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ugt1
    password: Welcome@123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect